// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chirpy_red_upgrade.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const chirpyRedUpgrade = `-- name: ChirpyRedUpgrade :exec

UPDATE users
SET IS_CHIRPY_RED = TRUE
WHERE ID = $1
`

func (q *Queries) ChirpyRedUpgrade(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, chirpyRedUpgrade, id)
	return err
}
