// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_hashed_password.sql

package database

import (
	"context"
)

const getHashedPassword = `-- name: GetHashedPassword :one
SELECT id, created_at, updated_at, email, hashed_password FROM USERS
WHERE email = $1
`

func (q *Queries) GetHashedPassword(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getHashedPassword, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
