// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_users_email_and_password.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserEmailAndPassword = `-- name: UpdateUserEmailAndPassword :exec
UPDATE users
SET EMAIL = $2, HASHED_PASSWORD = $3
WHERE ID = $1
`

type UpdateUserEmailAndPasswordParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
}

func (q *Queries) UpdateUserEmailAndPassword(ctx context.Context, arg UpdateUserEmailAndPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserEmailAndPassword, arg.ID, arg.Email, arg.HashedPassword)
	return err
}
