// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_from_refresh_token.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const userFromRefreshToken = `-- name: UserFromRefreshToken :one
SELECT USER_ID FROM refresh_tokens
WHERE TOKEN = $1 
AND EXPIRES_AT > NOW()
AND REVOKED_AT IS NULL
`

func (q *Queries) UserFromRefreshToken(ctx context.Context, token string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, userFromRefreshToken, token)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
